2020-11-15 15:42:18,356 ERROR: Exception on / [GET] [in f:\python projects\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "F:\python projects\microblog\app\main\routes.py", line 173, in before_request
    g.locale = str(get_locale())
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "F:\python projects\microblog\app\__init__.py", line 89, in get_locale
    return request.accept_languages.best_match(create_app.config['LANGUAGES'])
NameError: name 'app' is not defined
2020-11-15 15:42:22,543 ERROR: Exception on /favicon.ico [GET] [in f:\python projects\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "f:\python projects\microblog\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "f:\python projects\microblog\venv\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "F:\python projects\microblog\app\errors\handlers.py", line 8, in not_found_error
    return render_template('errors/404.html'), 404
  File "f:\python projects\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "f:\python projects\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "f:\python projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "f:\python projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "f:\python projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "F:\python projects\microblog\app\templates\errors\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "F:\python projects\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "f:\python projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "f:\python projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "f:\python projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 6, in block "html"
    {%- block head %}
  File "f:\python projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 7, in block "head"
    <title>{% block title %}{{title|default}}{% endblock title %}</title>
  File "F:\python projects\microblog\app\templates\base.html", line 4, in block "title"
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
  File "f:\python projects\microblog\venv\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "f:\python projects\microblog\venv\lib\site-packages\jinja2\ext.py", line 150, in gettext
    rv = __context.call(func, __string)
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 109, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 209, in get_translations
    return get_domain().get_translations()
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 554, in get_translations
    locale = get_locale()
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "F:\python projects\microblog\app\__init__.py", line 89, in get_locale
    return request.accept_languages.best_match(create_app.config['LANGUAGES'])
NameError: name 'app' is not defined
2020-11-15 15:43:23,708 INFO: Microblog startup [in F:\python projects\microblog\app\__init__.py:83]
2020-11-15 15:43:28,218 ERROR: Exception on / [GET] [in f:\python projects\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "f:\python projects\microblog\venv\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "F:\python projects\microblog\app\main\routes.py", line 173, in before_request
    g.locale = str(get_locale())
  File "f:\python projects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "F:\python projects\microblog\app\__init__.py", line 89, in get_locale
    return request.accept_languages.best_match(create_app.config['LANGUAGES'])
AttributeError: 'function' object has no attribute 'config'
